{"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate\/loginrequiredbysaleskeyboard()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate\/loginrequiredbysaleskeyboard()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate"]]},"metadata":{"roleHeading":"Instance Method","required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loginRequiredBySalesKeyboard"}],"title":"loginRequiredBySalesKeyboard()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate(im)loginRequiredBySalesKeyboard","modules":[{"name":"GCBuzzKeySDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate\/loginRequiredBySalesKeyboard()"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"GCKeyboardUtilsDelegate returns callback from GCKeyboardUtils for particular action required","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate","title":"GCKeyboardUtilsDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","navigatorTitle":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate/loginRequiredBySalesKeyboard()":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate\/loginRequiredBySalesKeyboard()","abstract":[],"required":true,"navigatorTitle":[{"text":"loginRequiredBySalesKeyboard","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate\/loginrequiredbysaleskeyboard()","title":"loginRequiredBySalesKeyboard()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"loginRequiredBySalesKeyboard","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"loginRequiredBySalesKeyboard"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GCKeyboardUtilsDelegate","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/navigatorTitle","op":"replace"},{"value":"loginRequiredBySalesKeyboard","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate~1loginRequiredBySalesKeyboard()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate~1loginRequiredBySalesKeyboard()\/fragments","op":"replace"}]}]}