{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"setDeviceFCMTokenWithToken:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDeviceFCMToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"GCBuzzKeySDK"}],"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults(im)setDeviceFCMTokenWithToken:","role":"symbol","symbolKind":"method","title":"setDeviceFCMToken(token:)"},"abstract":[{"type":"text","text":"Set device FCM token using following method"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setdevicefcmtoken(token:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setdevicefcmtoken(token:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setDeviceFCMToken(token:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDeviceFCMToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/setDeviceFCMToken(token:)":{"navigatorTitle":[{"kind":"identifier","text":"setDeviceFCMTokenWithToken:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDeviceFCMToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"text":"Set device FCM token using following method","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setdevicefcmtoken(token:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setDeviceFCMToken(token:)","title":"setDeviceFCMToken(token:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setDeviceFCMTokenWithToken:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDeviceFCMTokenWithToken:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setDeviceFCMTokenWithToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title","value":"GCUserDefaults","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments","value":[{"text":"GCUserDefaults","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle","value":[{"text":"GCUserDefaults","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setDeviceFCMToken(token:)\/title","value":"setDeviceFCMTokenWithToken:","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setDeviceFCMToken(token:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDeviceFCMTokenWithToken:","kind":"identifier"}],"op":"replace"}]}]}