{"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","kind":"typeIdentifier","text":"GCKeyboardUtilsDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils"]]},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","title":"delegate","externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils(py)delegate","modules":[{"name":"GCBuzzKeySDK"}],"symbolKind":"property","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/delegate":{"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/delegate","title":"delegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","kind":"symbol","title":"GCKeyboardUtilsDelegate","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"GCKeyboardUtilsDelegate returns callback from GCKeyboardUtils for particular action required"}],"navigatorTitle":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils":{"title":"GCKeyboardUtils","navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils","abstract":[{"type":"text","text":"Access this class in following method of AppDelegate"},{"type":"text","text":" "},{"type":"text","text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool"},{"type":"text","text":" "},{"type":"text","text":"This class will handle deeplink from keyboard to App using URL scheme"},{"type":"text","text":" "},{"type":"text","text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtils","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","text":"id<GCKeyboardUtilsDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/title","op":"replace","value":"GCKeyboardUtilsDelegate"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/fragments","op":"replace","value":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/navigatorTitle","op":"replace","value":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/title","op":"replace","value":"GCKeyboardUtils"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/fragments","op":"replace","value":[{"kind":"identifier","text":"GCKeyboardUtils"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/navigatorTitle","op":"replace","value":[{"text":"GCKeyboardUtils","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}