{"hierarchy":{"paths":[[]]},"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APICallError","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ActivityIndicator","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CoreDataManager","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSDKManager","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBBackgroundView","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBBarProgressView","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUD","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBRoundProgressView","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/NetworkAdapter","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManager"],"generated":true,"anchor":"Classes","title":"Classes"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIRequest","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/BaseRouterProtocol","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDDelegate","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected"],"generated":true,"anchor":"Protocols","title":"Protocols"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIConstants","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIError","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVSet","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Constraint","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginRequestBody","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginResponse","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginResponseData","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/UserDefaultsUtils"],"anchor":"Structures","title":"Structures"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressMaxOffset"],"anchor":"Variables","title":"Variables"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/plog(_:_:_:_:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/setLanguage(language:)"],"anchor":"Functions","title":"Functions"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/==(_:_:)"],"anchor":"Operators","title":"Operators"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Identifier","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDCompletionBlock","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PathParams","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/QueryParams","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RequestBody","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RequestHeaders","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ResponseArray","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ResponseObject"],"anchor":"Type-Aliases","title":"Type Aliases"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIResult","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVRange","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVScrollDirection","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVSelectionType","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVShape","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ContainingAppLaunchOption","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ContainingAppLaunchOptionKeys","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LocalizationKeys","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDAnimation","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDBackgroundStyle","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDMode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Theme"],"anchor":"Enumerations","title":"Enumerations"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RxSwift","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/UIKit"],"anchor":"Extended-Modules","title":"Extended Modules"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard UI and lifecycle"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Hotkey(Keyboard Screens) rendering and updates"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"User education flows","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Redirecting users to system settings"}]}]}]},{"level":2,"type":"heading","anchor":"HotKey-Overview","text":"HotKey Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An example of a Hotkey could be a payments hotkey which handles screens related to payments, such as displaying payment options, processing transactions, and showing transaction history. Another example could be a beneficiary hotkey that manages screens for adding, viewing, and managing beneficiaries. Based on the requirements and backend APIs the hotkeys can be customized to provide relevant functionalities to users. Designs and API contracts have to be agreed upon before implementation."}]},{"level":2,"type":"heading","anchor":"Integration-Steps","text":"Integration Steps"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To integrate the GCBuzzKeySDK into your iOS application, follow these steps:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Add a custom keyboard target to your iOS application. This can be added from Xcode by selecting File > New > Target and choosing “Custom Keyboard Extension” from the list of available templates."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the GCBuzzKeySDK framework to your custom keyboard target. You can do this by dragging and dropping the framework into your Xcode project and ensuring it is included in the “Link Binary With Libraries” section of your keyboard target’s build phases. Make sure that the framework is added with ‘Do not embed’ option."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the supporting GCKeyboardKitSDK.framework and GCPredicts.framework as well to the keyboard extension target with the ‘Do not embed’ option."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Add Associated Domains capability to both the main app target and keyboard extension target. In the Associated Domains section, add the following entry: "},{"type":"codeVoice","code":"com:gcsaleskeyboard"},{"type":"text","text":". This is required for deeplinking support."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Add the following keys to the Info.plist of your keyboard extension target:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"RequestsOpenAccess","type":"codeVoice"},{"text":" set to ","type":"text"},{"code":"YES","type":"codeVoice"},{"text":". This allows the keyboard to have full access to network resources.","type":"text"}]}]}],"type":"unorderedList"}]}]},{"level":2,"type":"heading","anchor":"Code-Integration","text":"Code Integration"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"In the custom keyboard extension’s main view controller, import the GCBuzzKeySDK framework:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["import GCBuzzKeySDK"]}]},{"content":[{"inlineContent":[{"text":"Update the keyboard view controller to inherit from ","type":"text"},{"code":"GCKeyboardViewController","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["class KeyboardViewController: GCKeyboardViewController {","    \/\/ Your custom implementation","}"],"syntax":"swift"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize the GCBuzzKeySDK with the login token in the "},{"type":"codeVoice","code":"viewDidLoad"},{"type":"text","text":" method of your keyboard view controller:"}]},{"type":"codeListing","code":["override func viewDidLoad() {","    super.viewDidLoad()","    GCUserDefaults.shared.setLoginToken(\"your_login_token\")","   }"],"syntax":"swift"}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"role":"collection","title":"GCBuzzKeySDK","roleHeading":"Framework","symbolKind":"module","externalID":"GCBuzzKeySDK"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk"]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUDDelegate":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/mbprogresshuddelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDDelegate"}],"title":"MBProgressHUDDelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDDelegate"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/BaseRouterProtocol":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/BaseRouterProtocol","url":"\/documentation\/gcbuzzkeysdk\/baserouterprotocol","type":"topic","navigatorTitle":[{"text":"BaseRouterProtocol","kind":"identifier"}],"title":"BaseRouterProtocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseRouterProtocol","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/Theme":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Theme","url":"\/documentation\/gcbuzzkeysdk\/theme","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Theme"}],"title":"Theme","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil":{"title":"AuthUtil","abstract":[{"type":"text","text":"Class for auth related details like keyboard access and user login status"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/authutil","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthUtil","kind":"identifier"}],"navigatorTitle":[{"text":"AuthUtil","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/ResponseObject":{"title":"ResponseObject","abstract":[],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ResponseObject","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/responseobject","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseObject"}],"navigatorTitle":[{"kind":"identifier","text":"ResponseObject"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PathParams":{"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/pathparams","title":"PathParams","navigatorTitle":[{"kind":"identifier","text":"PathParams"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PathParams","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PathParams"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/UserDefaultsUtils":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserDefaultsUtils"}],"navigatorTitle":[{"text":"UserDefaultsUtils","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/userdefaultsutils","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/UserDefaultsUtils","abstract":[],"kind":"symbol","role":"symbol","title":"UserDefaultsUtils"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/LoginResponse":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponse"}],"title":"LoginResponse","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginResponse","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/loginresponse","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginResponse"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils":{"title":"GCKeyboardUtils","navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils","abstract":[{"type":"text","text":"Access this class in following method of AppDelegate"},{"type":"text","text":" "},{"type":"text","text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool"},{"type":"text","text":" "},{"type":"text","text":"This class will handle deeplink from keyboard to App using URL scheme"},{"type":"text","text":" "},{"type":"text","text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtils","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUD":{"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUD"}],"title":"MBProgressHUD","type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUD","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUD"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus","url":"\/documentation\/gcbuzzkeysdk\/cvstatus","role":"symbol","navigatorTitle":[{"text":"CVStatus","kind":"identifier"}],"title":"CVStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVStatus","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUDMode":{"role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBProgressHUDMode","kind":"identifier"}],"navigatorTitle":[{"text":"MBProgressHUDMode","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDMode","url":"\/documentation\/gcbuzzkeysdk\/mbprogresshudmode","kind":"symbol","title":"MBProgressHUDMode"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/LocalizationKeys":{"title":"LocalizationKeys","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizationKeys","kind":"identifier"}],"navigatorTitle":[{"text":"LocalizationKeys","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LocalizationKeys","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/localizationkeys","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/RequestBody":{"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RequestBody","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBody"}],"navigatorTitle":[{"kind":"identifier","text":"RequestBody"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/requestbody","role":"symbol","kind":"symbol","title":"RequestBody"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday","title":"CVCalendarWeekday","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManager":{"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManager","kind":"identifier"}],"navigatorTitle":[{"text":"PropertyGuruServiceManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanager","role":"symbol","kind":"symbol","title":"PropertyGuruServiceManager"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVSet":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CVSet","kind":"identifier"}],"abstract":[],"title":"CVSet","url":"\/documentation\/gcbuzzkeysdk\/cvset","role":"symbol","navigatorTitle":[{"text":"CVSet","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVSet"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVShape":{"url":"\/documentation\/gcbuzzkeysdk\/cvshape","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVShape"}],"title":"CVShape","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVShape","navigatorTitle":[{"text":"CVShape","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/APICallError":{"url":"\/documentation\/gcbuzzkeysdk\/apicallerror","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"APICallError"}],"title":"APICallError","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APICallError","navigatorTitle":[{"kind":"identifier","text":"APICallError"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/RequestHeaders":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestHeaders"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This Protocol Must be extende"},{"type":"text","text":" "},{"type":"text","text":"func asURLRequest() throws -> URLRequest {"},{"type":"text","text":" "},{"type":"text","text":"<#code#>"},{"type":"text","text":" "},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"d by all the Routers. Defines Path, Method, Parameters, Body"}],"navigatorTitle":[{"kind":"identifier","text":"RequestHeaders"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RequestHeaders","url":"\/documentation\/gcbuzzkeysdk\/requestheaders","title":"RequestHeaders"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/ResponseArray":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseArray","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ResponseArray","role":"symbol","title":"ResponseArray","navigatorTitle":[{"text":"ResponseArray","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/responsearray","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CoreDataManager":{"title":"CoreDataManager","navigatorTitle":[{"kind":"identifier","text":"CoreDataManager"}],"url":"\/documentation\/gcbuzzkeysdk\/coredatamanager","abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CoreDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreDataManager"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/LoginRequestBody":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoginRequestBody","kind":"identifier"}],"navigatorTitle":[{"text":"LoginRequestBody","kind":"identifier"}],"abstract":[],"title":"LoginRequestBody","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/loginrequestbody","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginRequestBody"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode","title":"CVCalendarViewPresentationMode","navigatorTitle":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"abstract":[],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUDCompletionBlock":{"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDCompletionBlock","title":"MBProgressHUDCompletionBlock","url":"\/documentation\/gcbuzzkeysdk\/mbprogresshudcompletionblock","kind":"symbol","navigatorTitle":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/APIError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}],"title":"APIError","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/apierror","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIError"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/RxSwift":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/RxSwift","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/rxswift","title":"RxSwift","type":"topic","kind":"symbol","role":"collection"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/NetworkAdapter":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/NetworkAdapter","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/networkadapter","title":"NetworkAdapter","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkAdapter","kind":"identifier"}],"navigatorTitle":[{"text":"NetworkAdapter","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCBuzzKeySDKVersionString":{"type":"topic","abstract":[{"type":"text","text":"Project version string for GCBuzzKeySDK."}],"url":"\/documentation\/gcbuzzkeysdk\/gcbuzzkeysdkversionstring","kind":"symbol","fragments":[{"text":"GCBuzzKeySDKVersionString","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCBuzzKeySDKVersionString","title":"GCBuzzKeySDKVersionString"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController":{"kind":"symbol","title":"GCKeyboardViewController","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","abstract":[{"text":"Add Custom Keyboard extension to the application.","type":"text"},{"text":" ","type":"text"},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GCKeyboardViewController"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardViewController"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/QueryParams":{"navigatorTitle":[{"text":"QueryParams","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/queryparams","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryParams","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/QueryParams","title":"QueryParams"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressMaxOffset":{"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/mbprogressmaxoffset","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBProgressMaxOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressMaxOffset","title":"MBProgressMaxOffset"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/plog(_:_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"plog","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"@autoclosure","kind":"attribute"},{"text":" () -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:12GCBuzzKeySDK4plogyyxyXK_S2SSitlF1TL_xmfp"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/plog(_:_:_:_:)","title":"plog(_:_:_:_:)","role":"symbol","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/plog(_:_:_:_:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVSelectionType":{"url":"\/documentation\/gcbuzzkeysdk\/cvselectiontype","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVSelectionType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CVSelectionType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVSelectionType","title":"CVSelectionType","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBRoundProgressView":{"kind":"symbol","title":"MBRoundProgressView","navigatorTitle":[{"text":"MBRoundProgressView","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBRoundProgressView","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/mbroundprogressview","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBRoundProgressView"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBBarProgressView":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/mbbarprogressview","type":"topic","title":"MBBarProgressView","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBBarProgressView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBBarProgressView","kind":"identifier"}],"navigatorTitle":[{"text":"MBBarProgressView","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/Constraint":{"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Constraint"}],"url":"\/documentation\/gcbuzzkeysdk\/constraint","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Constraint","title":"Constraint","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Constraint"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[],"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","type":"topic","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/setLanguage(language:)":{"kind":"symbol","title":"setLanguage(language:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLanguage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/gcbuzzkeysdk\/setlanguage(language:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/setLanguage(language:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBBackgroundView":{"title":"MBBackgroundView","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBBackgroundView","role":"symbol","type":"topic","navigatorTitle":[{"text":"MBBackgroundView","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBBackgroundView","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/mbbackgroundview","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/Identifier":{"title":"Identifier","navigatorTitle":[{"text":"Identifier","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/identifier","abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/Identifier","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Identifier","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"title":"CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","kind":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","kind":"symbol","title":"GCKeyboardUtilsDelegate","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"GCKeyboardUtilsDelegate returns callback from GCKeyboardUtils for particular action required"}],"navigatorTitle":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/ContainingAppLaunchOptionKeys":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ContainingAppLaunchOptionKeys","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/containingapplaunchoptionkeys","title":"ContainingAppLaunchOptionKeys","navigatorTitle":[{"text":"ContainingAppLaunchOptionKeys","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainingAppLaunchOptionKeys","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/ActivityIndicator":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActivityIndicator"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicator"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/activityindicator","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ActivityIndicator","kind":"symbol","title":"ActivityIndicator"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/APIRequest":{"title":"APIRequest","navigatorTitle":[{"kind":"identifier","text":"APIRequest"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIRequest","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIRequest"}],"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/apirequest"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent":{"type":"topic","role":"symbol","title":"CVPresent","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent","navigatorTitle":[{"kind":"identifier","text":"CVPresent"}],"url":"\/documentation\/gcbuzzkeysdk\/cvpresent","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPresent"}],"kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/APIConstants":{"type":"topic","role":"symbol","title":"APIConstants","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIConstants","navigatorTitle":[{"kind":"identifier","text":"APIConstants"}],"url":"\/documentation\/gcbuzzkeysdk\/apiconstants","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIConstants"}],"kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVRange":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVRange","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvrange","abstract":[],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVRange","navigatorTitle":[{"text":"CVRange","kind":"identifier"}],"kind":"symbol","title":"CVRange","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/UIKit":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/UIKit","type":"topic","title":"UIKit","role":"collection","url":"\/documentation\/gcbuzzkeysdk\/uikit"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVScrollDirection":{"navigatorTitle":[{"kind":"identifier","text":"CVScrollDirection"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVScrollDirection","kind":"symbol","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/cvscrolldirection","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVScrollDirection","kind":"identifier"}],"role":"symbol","title":"CVScrollDirection"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/==(_:_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:12GCBuzzKeySDK15CVSelectionTypeO","text":"CVSelectionType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:12GCBuzzKeySDK15CVSelectionTypeO","text":"CVSelectionType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/==(_:_:)","title":"==(_:_:)","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/==(_:_:)","role":"symbol","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/APIResult":{"kind":"symbol","navigatorTitle":[{"text":"APIResult","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/APIResult","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/apiresult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIResult"}],"title":"APIResult","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUDAnimation":{"title":"MBProgressHUDAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDAnimation"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/mbprogresshudanimation","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDAnimation"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/LoginResponseData":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoginResponseData","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/loginresponsedata","navigatorTitle":[{"text":"LoginResponseData","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/LoginResponseData","kind":"symbol","title":"LoginResponseData","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSDKManager":{"navigatorTitle":[{"text":"GCSDKManager","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSDKManager","abstract":[],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsdkmanager","title":"GCSDKManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSDKManager","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManagerInjected":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PropertyGuruServiceManagerInjected"}],"title":"PropertyGuruServiceManagerInjected","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCBuzzKeySDKVersionNumber":{"type":"topic","title":"GCBuzzKeySDKVersionNumber","fragments":[{"text":"GCBuzzKeySDKVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for GCBuzzKeySDK."}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcbuzzkeysdkversionnumber","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCBuzzKeySDKVersionNumber"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/MBProgressHUDBackgroundStyle":{"title":"MBProgressHUDBackgroundStyle","role":"symbol","navigatorTitle":[{"text":"MBProgressHUDBackgroundStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDBackgroundStyle"}],"type":"topic","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/mbprogresshudbackgroundstyle","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/MBProgressHUDBackgroundStyle"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/ContainingAppLaunchOption":{"title":"ContainingAppLaunchOption","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/containingapplaunchoption","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContainingAppLaunchOption"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainingAppLaunchOption"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/ContainingAppLaunchOption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Classes","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"],"generated":true,"title":"Classes"},{"anchor":"Protocols","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate"],"generated":true,"title":"Protocols"},{"anchor":"Variables","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCBuzzKeySDKVersionNumber","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCBuzzKeySDKVersionString"],"generated":true,"title":"Variables"},{"anchor":"Enumerations","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"],"generated":true,"title":"Enumerations"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/title","value":"AuthUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/fragments","value":[{"text":"AuthUtil","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/navigatorTitle","value":[{"text":"AuthUtil","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/title","value":"GCKeyboardUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/fragments","value":[{"text":"GCKeyboardUtils","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/navigatorTitle","value":[{"text":"GCKeyboardUtils","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/title","value":"CVStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/fragments","value":[{"text":"CVStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/navigatorTitle","value":[{"text":"CVStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/title","value":"CVCalendarWeekday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/fragments","value":[{"text":"CVCalendarWeekday","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/navigatorTitle","value":[{"kind":"identifier","text":"CVCalendarWeekday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/title","value":"CVCalendarViewPresentationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/fragments","value":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/navigatorTitle","value":[{"text":"CVCalendarViewPresentationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/title","value":"GCKeyboardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/fragments","value":[{"kind":"identifier","text":"GCKeyboardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/navigatorTitle","value":[{"text":"GCKeyboardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title","value":"CVWeekdaySymbolType"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle","value":[{"text":"CVWeekdaySymbolType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/title","value":"GCKeyboardUtilsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/fragments","value":[{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/navigatorTitle","op":"replace","value":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/title","op":"replace","value":"CVPresent"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVPresent"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/navigatorTitle","op":"replace","value":[{"text":"CVPresent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title","op":"replace","value":"GCUserDefaults"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments","op":"replace","value":[{"kind":"identifier","text":"GCUserDefaults"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle","op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}]}]}]}