{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"GCBuzzKeySDK"}],"title":"init","symbolKind":"method","externalID":"c:@M@GCBuzzKeySDK@objc(cs)AuthUtil(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/authutil\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil/init":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/authutil\/init","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol","title":"init","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil":{"title":"AuthUtil","abstract":[{"type":"text","text":"Class for auth related details like keyboard access and user login status"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/authutil","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthUtil","kind":"identifier"}],"navigatorTitle":[{"text":"AuthUtil","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/title","op":"replace","value":"AuthUtil"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/fragments","op":"replace","value":[{"text":"AuthUtil","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/navigatorTitle","op":"replace","value":[{"text":"AuthUtil","kind":"identifier"}]}]}]}