{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/RawRepresentable-Implementations"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}]}]}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/cvstatus\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"GCBuzzKeySDK"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@GCBuzzKeySDK@E@CVStatus","roleHeading":"Instance Method","title":"hash(into:)"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/hash(into:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/rawrepresentable-implementations","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvstatus","type":"topic","title":"CVStatus","navigatorTitle":[{"text":"CVStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVStatus","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/hash(into:)","kind":"symbol","abstract":[],"type":"topic","title":"hash(into:)","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CVStatus","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/title"},{"value":[{"text":"CVStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/fragments"},{"value":[{"text":"CVStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/navigatorTitle"}]}]}