{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController\/initWithCoder:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardViewController(im)initWithCoder:","roleHeading":"Instance Method","modules":[{"name":"GCBuzzKeySDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","symbolKind":"method","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController"]]},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk","type":"topic","role":"collection"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController/initWithCoder:":{"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller\/initwithcoder:","kind":"symbol","title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController\/initWithCoder:","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController":{"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Add Custom Keyboard extension to the application."},{"type":"text","text":" "},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"type":"topic","title":"GCKeyboardViewController","role":"symbol","navigatorTitle":[{"text":"GCKeyboardViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/title","value":"GCKeyboardViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/fragments","value":[{"kind":"identifier","text":"GCKeyboardViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GCKeyboardViewController"}],"op":"replace"}]}]}