{"metadata":{"externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeBadRequest","modules":[{"name":"GCBuzzKeySDK"}],"title":"HTTPStatusCode.badRequest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badRequest","kind":"identifier"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeBadRequest"}],"roleHeading":"Case"},"sections":[],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/badrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/badrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badRequest","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badRequest"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/badRequest":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badRequest","kind":"identifier"}],"title":"HTTPStatusCode.badRequest","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/badrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeBadRequest"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badRequest"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HTTPStatusCodeBadRequest","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"HTTPStatusCodeBadRequest","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"HTTPStatusCodeBadRequest","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HTTPStatusCode","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title"},{"value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments"},{"value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle"},{"value":"HTTPStatusCodeBadRequest","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badRequest\/title"},{"value":[{"text":"HTTPStatusCodeBadRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badRequest\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}