{"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"GCBuzzKeySDK"}],"title":"Equatable Implementations"},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/!=(_:_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/Equatable-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/!=(_:_:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/!=(_:_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"!=(_:_:)","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/!=(_:_:)","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","value":[{"text":"HTTPStatusCode","kind":"identifier"}]}]}]}