{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerError"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/internalservererror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/internalservererror"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/internalServerError"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"HTTPStatusCodeInternalServerError","kind":"identifier"}],"modules":[{"name":"GCBuzzKeySDK"}],"role":"symbol","externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeInternalServerError","roleHeading":"Case","title":"HTTPStatusCode.internalServerError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalServerError","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[],"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","type":"topic","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/internalServerError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/internalServerError","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/internalservererror","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalServerError","kind":"identifier"}],"navigatorTitle":[{"text":"HTTPStatusCodeInternalServerError","kind":"identifier"}],"title":"HTTPStatusCode.internalServerError"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"HTTPStatusCodeInternalServerError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"HTTPStatusCodeInternalServerError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"HTTPStatusCodeInternalServerError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","value":"HTTPStatusCode","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","value":[{"kind":"identifier","text":"HTTPStatusCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1internalServerError\/title","value":"HTTPStatusCodeInternalServerError","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1internalServerError\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeInternalServerError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}