{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/loopDetected"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopDetected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/loopdetected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/loopdetected"]}],"metadata":{"role":"symbol","modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeLoopDetected"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopDetected","kind":"identifier"}],"externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeLoopDetected","title":"HTTPStatusCode.loopDetected"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"sections":[],"abstract":[{"type":"text","text":"Internal Server Error: 500"}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/loopDetected":{"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/loopdetected","title":"HTTPStatusCode.loopDetected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopDetected","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/loopDetected","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeLoopDetected"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HTTPStatusCodeLoopDetected","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HTTPStatusCodeLoopDetected","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeLoopDetected"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HTTPStatusCodeLoopDetected","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1loopDetected\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeLoopDetected"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1loopDetected\/fragments"},{"op":"replace","value":"HTTPStatusCode","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCode"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments"},{"op":"replace","value":[{"text":"HTTPStatusCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle"}]}]}