{"abstract":[{"type":"text","text":"Internal Server Error: 500"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceUnavailable","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/serviceUnavailable","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/serviceunavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/serviceunavailable"]}],"metadata":{"symbolKind":"case","title":"HTTPStatusCode.serviceUnavailable","externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeServiceUnavailable","roleHeading":"Case","navigatorTitle":[{"text":"HTTPStatusCodeServiceUnavailable","kind":"identifier"}],"modules":[{"name":"GCBuzzKeySDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceUnavailable","kind":"identifier"}]},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/serviceUnavailable":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/serviceUnavailable","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/serviceunavailable","navigatorTitle":[{"text":"HTTPStatusCodeServiceUnavailable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceUnavailable","kind":"identifier"}],"title":"HTTPStatusCode.serviceUnavailable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"HTTPStatusCodeServiceUnavailable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeServiceUnavailable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HTTPStatusCodeServiceUnavailable"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1serviceUnavailable\/title","value":"HTTPStatusCodeServiceUnavailable","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1serviceUnavailable\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeServiceUnavailable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","value":"HTTPStatusCode","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace"}]}]}