{"kind":"article","identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType"]]},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"title":"CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","kind":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/!=(_:_:)":{"kind":"symbol","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/!=(_:_:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"CVWeekdaySymbolType","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title"},{"value":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments"},{"value":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}