{"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/veryShort","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"veryShort","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"veryShort"}],"title":"CVWeekdaySymbolType.veryShort","externalID":"c:@M@GCBuzzKeySDK@E@CVWeekdaySymbolType@CVWeekdaySymbolTypeVeryShort","role":"symbol","modules":[{"name":"GCBuzzKeySDK"}],"navigatorTitle":[{"kind":"identifier","text":"CVWeekdaySymbolTypeVeryShort"}]},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/veryshort"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/veryshort"]}],"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVWeekdaySymbolType"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"kind":"symbol","title":"CVWeekdaySymbolType","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/veryShort":{"title":"CVWeekdaySymbolType.veryShort","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"veryShort","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/veryShort","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolTypeVeryShort","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/veryshort"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CVWeekdaySymbolTypeVeryShort","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"CVWeekdaySymbolTypeVeryShort","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"CVWeekdaySymbolTypeVeryShort","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CVWeekdaySymbolType","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle","op":"replace"},{"value":"CVWeekdaySymbolTypeVeryShort","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1veryShort\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CVWeekdaySymbolTypeVeryShort"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1veryShort\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}