{"abstract":[{"type":"text","text":"Call this class method as shown below in AppDelegate"},{"type":"text","text":" "},{"type":"text","text":"func application(_ app: UIApplication, open url: URL,"},{"type":"text","text":" "},{"type":"text","text":"options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {"},{"type":"text","text":" "},{"type":"text","text":"GCKeyboardUtils.shared.handle(app, open: url, options: options, target: window.rootViewController!)"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"open","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey","kind":"typeIdentifier","text":"OpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":")"}],"role":"symbol","title":"handle(_:open:options:target:)","navigatorTitle":[{"kind":"identifier","text":"handle:open:options:target:"}],"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils(im)handle:open:options:target:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"GCBuzzKeySDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"app","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"open","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/handle(_:open:options:target:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/handle(_:open:options:target:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/handle(_:open:options:target:)"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils":{"navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}],"title":"GCKeyboardUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardUtils"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","role":"symbol","kind":"symbol","abstract":[{"text":"Access this class in following method of AppDelegate","type":"text"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool","type":"text"},{"text":" ","type":"text"},{"text":"This class will handle deeplink from keyboard to App using URL scheme","type":"text"},{"text":" ","type":"text"},{"text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"type":"topic","title":"GCBuzzKeySDK","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","role":"collection","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/handle(_:open:options:target:)":{"navigatorTitle":[{"text":"handle:open:options:target:","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/handle(_:open:options:target:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/handle(_:open:options:target:)","type":"topic","abstract":[{"text":"Call this class method as shown below in AppDelegate","type":"text"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL,","type":"text"},{"text":" ","type":"text"},{"text":"options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {","type":"text"},{"text":" ","type":"text"},{"text":"GCKeyboardUtils.shared.handle(app, open: url, options: options, target: window.rootViewController!)","type":"text"}],"title":"handle(_:open:options:target:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"open","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":".","kind":"text"},{"text":"OpenURLOptionsKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"handle:open:options:target:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"handle:open:options:target:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"handle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"app"},{"kind":"text","text":" "},{"kind":"identifier","text":"open:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"target:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"target"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GCKeyboardUtils","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GCKeyboardUtils"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/fragments","op":"replace"},{"value":[{"text":"GCKeyboardUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/navigatorTitle","op":"replace"},{"value":"handle:open:options:target:","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1handle(_:open:options:target:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"handle:open:options:target:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1handle(_:open:options:target:)\/fragments","op":"replace"}]}]}