{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKeyboardUtils","kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/shared"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils"]]},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/shared","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"shared","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils","kind":"typeIdentifier","text":"GCKeyboardUtils"}],"symbolKind":"property","externalID":"s:12GCBuzzKeySDK15GCKeyboardUtilsC6sharedACvpZ","modules":[{"name":"GCBuzzKeySDK"}]},"sections":[],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/shared":{"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/shared","kind":"symbol","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKeyboardUtils","kind":"typeIdentifier","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/shared","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"role":"collection","title":"GCBuzzKeySDK","type":"topic","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils","abstract":[{"type":"text","text":"Access this class in following method of AppDelegate"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool","type":"text"},{"text":" ","type":"text"},{"text":"This class will handle deeplink from keyboard to App using URL scheme","type":"text"},{"text":" ","type":"text"},{"text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks","type":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtils","kind":"identifier"}],"title":"GCKeyboardUtils","navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"GCKeyboardUtils","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/title"},{"value":[{"kind":"identifier","text":"GCKeyboardUtils"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/fragments"},{"value":[{"text":"GCKeyboardUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}