{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvstatus\/equatable-implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/!=(_:_:)"]}],"metadata":{"title":"Equatable Implementations","modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/!=(_:_:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/!=(_:_:)","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus","url":"\/documentation\/gcbuzzkeysdk\/cvstatus","role":"symbol","navigatorTitle":[{"text":"CVStatus","kind":"identifier"}],"title":"CVStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/title","value":"CVStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/fragments","value":[{"kind":"identifier","text":"CVStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/navigatorTitle","value":[{"kind":"identifier","text":"CVStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}