{"topicSections":[{"anchor":"Type-Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isOpenAccessGranted()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isUserLoggedIn()"],"title":"Type Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/authutil"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/authutil"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"abstract":[{"text":"Class for auth related details like keyboard access and user login status","type":"text"}],"kind":"symbol","metadata":{"roleHeading":"Class","externalID":"c:@M@GCBuzzKeySDK@objc(cs)AuthUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthUtil"}],"navigatorTitle":[{"kind":"identifier","text":"AuthUtil"}],"modules":[{"name":"GCBuzzKeySDK"}],"role":"symbol","symbolKind":"class","title":"AuthUtil"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthUtil","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"references":{"doc://com.gamechange.GCKeyboard/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil/isOpenAccessGranted()":{"abstract":[{"text":"Method to check if open access is granted for the keyboard","type":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isOpenAccessGranted()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isOpenAccessGranted"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOpenAccessGranted","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isOpenAccessGranted()","url":"\/documentation\/gcbuzzkeysdk\/authutil\/isopenaccessgranted()"},"doc://com.gamechange.GCKeyboard/objc(cs)NSObject":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s7CVarArgP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil/isUserLoggedIn()":{"role":"symbol","navigatorTitle":[{"text":"isUserLoggedIn","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isUserLoggedIn()","title":"isUserLoggedIn()","url":"\/documentation\/gcbuzzkeysdk\/authutil\/isuserloggedin()","kind":"symbol","abstract":[{"type":"text","text":"Method to check if user is logged in"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUserLoggedIn","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil/init":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/authutil\/init","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol","title":"init","abstract":[]},"doc://com.gamechange.GCKeyboard/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","title":"Swift.Equatable"},"doc://com.gamechange.GCKeyboard/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.gamechange.GCKeyboard/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","title":"RxSwift.ReactiveCompatible"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/AuthUtil":{"title":"AuthUtil","abstract":[{"type":"text","text":"Class for auth related details like keyboard access and user login status"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/authutil","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthUtil","kind":"identifier"}],"navigatorTitle":[{"text":"AuthUtil","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AuthUtil","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AuthUtil"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AuthUtil","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/init"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isOpenAccessGranted()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/AuthUtil\/isUserLoggedIn()"],"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthUtil","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isOpenAccessGranted","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil~1isOpenAccessGranted()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"isOpenAccessGranted","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil~1isOpenAccessGranted()\/fragments"},{"value":"isUserLoggedIn","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil~1isUserLoggedIn()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"isUserLoggedIn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil~1isUserLoggedIn()\/fragments"},{"value":"AuthUtil","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/title"},{"value":[{"kind":"identifier","text":"AuthUtil"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/fragments"},{"value":[{"kind":"identifier","text":"AuthUtil"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1AuthUtil\/navigatorTitle"}]}]}