{"metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"symbolKind":"enum","externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarWeekday","roleHeading":"Enumeration","title":"CVCalendarWeekday","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVCalendarWeekday"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/friday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/monday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/saturday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/sunday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/thursday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/tuesday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/wednesday"],"anchor":"Enumeration-Cases","generated":true},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/equatable-implementations"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/sunday":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/sunday","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sunday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/sunday","navigatorTitle":[{"text":"CVCalendarWeekdaySunday","kind":"identifier"}],"abstract":[],"type":"topic","title":"CVCalendarWeekday.sunday","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday","title":"CVCalendarWeekday","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/thursday":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/thursday","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thursday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/thursday","navigatorTitle":[{"text":"CVCalendarWeekdayThursday","kind":"identifier"}],"abstract":[],"type":"topic","title":"CVCalendarWeekday.thursday","role":"symbol"},"doc://com.gamechange.GCKeyboard/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/tuesday":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tuesday","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/tuesday","title":"CVCalendarWeekday.tuesday","navigatorTitle":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/tuesday"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/friday":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/friday","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/friday","navigatorTitle":[{"text":"CVCalendarWeekdayFriday","kind":"identifier"}],"abstract":[],"type":"topic","title":"CVCalendarWeekday.friday","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/init(rawValue:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/init(rawvalue:)","abstract":[],"type":"topic","title":"init(rawValue:)","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/RawRepresentable-Implementations":{"type":"topic","kind":"article","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/rawrepresentable-implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/saturday":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saturday","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/saturday","navigatorTitle":[{"text":"CVCalendarWeekdaySaturday","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/saturday","role":"symbol","title":"CVCalendarWeekday.saturday","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/wednesday":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/wednesday","title":"CVCalendarWeekday.wednesday","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/wednesday","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wednesday","kind":"identifier"}],"navigatorTitle":[{"text":"CVCalendarWeekdayWednesday","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/monday":{"navigatorTitle":[{"kind":"identifier","text":"CVCalendarWeekdayMonday"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/monday","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"monday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/monday","title":"CVCalendarWeekday.monday"},"doc://com.gamechange.GCKeyboard/SY":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CVCalendarWeekday"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekday"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CVCalendarWeekday","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/friday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/monday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/saturday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/sunday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/thursday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/tuesday","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/wednesday"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVCalendarWeekday"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1sunday\/title","value":"CVCalendarWeekdaySunday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1sunday\/fragments","value":[{"text":"CVCalendarWeekdaySunday","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/title","value":"CVCalendarWeekday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/navigatorTitle","value":[{"kind":"identifier","text":"CVCalendarWeekday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1thursday\/title","value":"CVCalendarWeekdayThursday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1thursday\/fragments","value":[{"text":"CVCalendarWeekdayThursday","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1tuesday\/title","value":"CVCalendarWeekdayTuesday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1tuesday\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1friday\/title","value":"CVCalendarWeekdayFriday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1friday\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekdayFriday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1saturday\/title","value":"CVCalendarWeekdaySaturday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1saturday\/fragments","value":[{"text":"CVCalendarWeekdaySaturday","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1wednesday\/title","value":"CVCalendarWeekdayWednesday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1wednesday\/fragments","value":[{"text":"CVCalendarWeekdayWednesday","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1monday\/title","value":"CVCalendarWeekdayMonday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1monday\/fragments","value":[{"text":"CVCalendarWeekdayMonday","kind":"identifier"}]}]}]}