{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"metadata":{"role":"symbol","symbolKind":"enum","navigatorTitle":[{"text":"CVPresent","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@GCBuzzKeySDK@E@CVPresent","title":"CVPresent","modules":[{"name":"GCBuzzKeySDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPresent"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvpresent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvpresent"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent"},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/not","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/present"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVPresent","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent/Equatable-Implementations":{"url":"\/documentation\/gcbuzzkeysdk\/cvpresent\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent/present":{"url":"\/documentation\/gcbuzzkeysdk\/cvpresent\/present","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/present","navigatorTitle":[{"text":"CVPresentPresent","kind":"identifier"}],"title":"CVPresent.present","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent/not":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"not","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/not","navigatorTitle":[{"text":"CVPresentNot","kind":"identifier"}],"title":"CVPresent.not","url":"\/documentation\/gcbuzzkeysdk\/cvpresent\/not"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent":{"type":"topic","role":"symbol","title":"CVPresent","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent","navigatorTitle":[{"kind":"identifier","text":"CVPresent"}],"url":"\/documentation\/gcbuzzkeysdk\/cvpresent","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPresent"}],"kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/cvpresent\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.gamechange.GCKeyboard/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ"},"doc://com.gamechange.GCKeyboard/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVPresent/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/init(rawValue:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/cvpresent\/init(rawvalue:)","role":"symbol"},"doc://com.gamechange.GCKeyboard/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CVPresent","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"CVPresent","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"CVPresent","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/not","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVPresent\/present"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVPresent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CVPresentPresent","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent~1present\/title"},{"op":"replace","value":[{"text":"CVPresentPresent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent~1present\/fragments"},{"op":"replace","value":"CVPresentNot","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent~1not\/title"},{"op":"replace","value":[{"text":"CVPresentNot","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent~1not\/fragments"},{"op":"replace","value":"CVPresent","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/title"},{"op":"replace","value":[{"text":"CVPresent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CVPresent"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVPresent\/navigatorTitle"}]}]}