{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardViewController","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"GCKeyboardViewController","modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"Class","navigatorTitle":[{"text":"GCKeyboardViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardViewController","kind":"identifier"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardViewController"},"abstract":[{"text":"Add Custom Keyboard extension to the application.","type":"text"},{"text":" ","type":"text"},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSCoding","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/s8SendableP","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIAppearanceContainer","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIContentContainer","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentMenuDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentPickerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIFocusEnvironment","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIStateRestoring","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextFieldDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextInputDelegate","doc:\/\/com.gamechange.GCKeyboard\/5UIKit23UITraitChangeObservableP","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITraitEnvironment","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ"},"doc://com.gamechange.GCKeyboard/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIResponderStandardEditActions"},"doc://com.gamechange.GCKeyboard/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController/initWithCoder:":{"title":"initWithCoder:","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller\/initwithcoder:","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController\/initWithCoder:","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.gamechange.GCKeyboard/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP"},"doc://com.gamechange.GCKeyboard/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UIKit.UINavigationControllerDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UINavigationControllerDelegate"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController":{"kind":"symbol","title":"GCKeyboardViewController","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","abstract":[{"text":"Add Custom Keyboard extension to the application.","type":"text"},{"text":" ","type":"text"},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GCKeyboardViewController"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardViewController"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIFocusEnvironment"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManagerInjected":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PropertyGuruServiceManagerInjected"}],"title":"PropertyGuruServiceManagerInjected","abstract":[]},"doc://com.gamechange.GCKeyboard/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.gamechange.GCKeyboard/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/5UIKit23UITraitChangeObservableP"},"doc://com.gamechange.GCKeyboard/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP"},"doc://com.gamechange.GCKeyboard/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.gamechange.GCKeyboard/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP"},"doc://com.gamechange.GCKeyboard/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIDocumentPickerDelegate":{"title":"UIKit.UIDocumentPickerDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentPickerDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIAppearanceContainer"},"doc://com.gamechange.GCKeyboard/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s8SendableP"},"doc://com.gamechange.GCKeyboard/objc(pl)UIDocumentMenuDelegate":{"type":"unresolvable","title":"UIKit.UIDocumentMenuDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentMenuDelegate"},"doc://com.gamechange.GCKeyboard/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject"},"doc://com.gamechange.GCKeyboard/objc(pl)UITextInputDelegate":{"type":"unresolvable","title":"UIKit.UITextInputDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextInputDelegate"},"doc://com.gamechange.GCKeyboard/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextFieldDelegate"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},"doc://com.gamechange.GCKeyboard/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIStateRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GCKeyboardViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GCKeyboardViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GCKeyboardViewController","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController\/initWithCoder:"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"GCSalesKeyBoardViewController","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCSalesKeyBoardViewController"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/title","value":"GCKeyboardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/fragments","value":[{"text":"GCKeyboardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/navigatorTitle","value":[{"text":"GCKeyboardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]}]}]}