{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCUserDefaults","kind":"identifier"}],"symbolKind":"class","title":"GCUserDefaults"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/clear()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setDeviceFCMToken(token:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setLoginToken(token:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/shared"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GCUserDefaults) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}]}]}],"abstract":[{"text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"references":{"doc://com.gamechange.GCKeyboard/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/setDeviceFCMToken(token:)":{"navigatorTitle":[{"kind":"identifier","text":"setDeviceFCMTokenWithToken:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDeviceFCMToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"text":"Set device FCM token using following method","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setdevicefcmtoken(token:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setDeviceFCMToken(token:)","title":"setDeviceFCMToken(token:)"},"doc://com.gamechange.GCKeyboard/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/shared":{"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults","text":"GCUserDefaults","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/shared","title":"shared","kind":"symbol"},"doc://com.gamechange.GCKeyboard/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH"},"doc://com.gamechange.GCKeyboard/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/7RxSwift18ReactiveCompatibleP":{"title":"RxSwift.ReactiveCompatible","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP"},"doc://com.gamechange.GCKeyboard/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/setLoginToken(token:)":{"type":"topic","navigatorTitle":[{"text":"setLoginTokenWithToken:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoginToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Set Login Access token using this method","type":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setLoginToken(token:)","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setlogintoken(token:)","title":"setLoginToken(token:)"},"doc://com.gamechange.GCKeyboard/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/clear()":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"clear","kind":"identifier"}],"title":"clear()","abstract":[{"text":"This method clear all userDefaults","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/clear()","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/clear()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"()"}]},"doc://com.gamechange.GCKeyboard/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GCUserDefaults","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GCUserDefaults"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/clear()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setDeviceFCMToken(token:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setLoginToken(token:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCUserDefaults","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"setDeviceFCMTokenWithToken:","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setDeviceFCMToken(token:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setDeviceFCMTokenWithToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setDeviceFCMToken(token:)\/fragments"},{"op":"replace","value":"GCUserDefaults","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GCUserDefaults"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments"},{"op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle"},{"op":"replace","value":"setLoginTokenWithToken:","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setLoginToken(token:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLoginTokenWithToken:"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setLoginToken(token:)\/fragments"},{"op":"replace","value":"clear","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1clear()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clear"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1clear()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}