{"metadata":{"externalID":"s:12GCBuzzKeySDK34PropertyGuruServiceManagerInjectedPAAE08propertyefG0AA0defG0Cvp::SYNTHESIZED::c:@M@GCBuzzKeySDK@objc(cs)GCSalesKeyBoardViewController","roleHeading":"Instance Property","extendedModule":"GCBuzzKeySDK","role":"symbol","title":"propertyGuruServiceManager","symbolKind":"property","modules":[{"name":"GCBuzzKeySDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"propertyGuruServiceManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PropertyGuruServiceManager","preciseIdentifier":"s:12GCBuzzKeySDK26PropertyGuruServiceManagerC","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/PropertyGuruServiceManagerInjected-Implementations"]]},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/propertyGuruServiceManager","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"PropertyGuruServiceManagerInjected.propertyGuruServiceManager","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanager"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyGuruServiceManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PropertyGuruServiceManager","kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManager","preciseIdentifier":"s:12GCBuzzKeySDK26PropertyGuruServiceManagerC"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManager":{"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManager","kind":"identifier"}],"navigatorTitle":[{"text":"PropertyGuruServiceManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanager","role":"symbol","kind":"symbol","title":"PropertyGuruServiceManager"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/PropertyGuruServiceManagerInjected-Implementations":{"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanagerinjected-implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/PropertyGuruServiceManagerInjected-Implementations","title":"PropertyGuruServiceManagerInjected Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/propertyGuruServiceManager":{"type":"topic","abstract":[],"title":"propertyGuruServiceManager","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanager","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyGuruServiceManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PropertyGuruServiceManager","kind":"typeIdentifier","preciseIdentifier":"s:12GCBuzzKeySDK26PropertyGuruServiceManagerC"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/propertyGuruServiceManager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}