{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVCalendarViewPresentationMode"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/monthView","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/weekView"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"metadata":{"navigatorTitle":[{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"modules":[{"name":"GCBuzzKeySDK"}],"symbolKind":"enum","role":"symbol","externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarViewPresentationMode","roleHeading":"Enumeration","title":"CVCalendarViewPresentationMode"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode"},"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/init(rawValue:)":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/monthView":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/monthview","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/monthView","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"monthView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CVCalendarViewPresentationModeMonthView"}],"title":"CVCalendarViewPresentationMode.monthView","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode","title":"CVCalendarViewPresentationMode","navigatorTitle":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"abstract":[],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/Equatable-Implementations":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/Equatable-Implementations","abstract":[],"kind":"article"},"doc://com.gamechange.GCKeyboard/SQ":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/RawRepresentable-Implementations":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/RawRepresentable-Implementations","type":"topic"},"doc://com.gamechange.GCKeyboard/SH":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/weekView":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/weekview","navigatorTitle":[{"kind":"identifier","text":"CVCalendarViewPresentationModeWeekView"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/weekView","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"weekView"}],"kind":"symbol","role":"symbol","title":"CVCalendarViewPresentationMode.weekView","type":"topic"},"doc://com.gamechange.GCKeyboard/SY":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"CVCalendarViewPresentationMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/monthView","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/weekView"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarViewPresentationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1monthView\/title","value":"CVCalendarViewPresentationModeMonthView","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1monthView\/fragments","value":[{"kind":"identifier","text":"CVCalendarViewPresentationModeMonthView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/title","value":"CVCalendarViewPresentationMode","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/fragments","value":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/navigatorTitle","value":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1weekView\/title","value":"CVCalendarViewPresentationModeWeekView","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1weekView\/fragments","value":[{"kind":"identifier","text":"CVCalendarViewPresentationModeWeekView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}