{"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/cvstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/cvstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus"},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVStatus"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"Enumeration","title":"CVStatus","navigatorTitle":[{"kind":"identifier","text":"CVStatus"}],"externalID":"c:@M@GCBuzzKeySDK@E@CVStatus"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/disabled","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/highlighted","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/in","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/out","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/selected"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVStatus","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/rawrepresentable-implementations","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/Equatable-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/equatable-implementations","kind":"article"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/selected":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/selected","type":"topic","title":"CVStatus.selected","role":"symbol","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/selected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"}],"navigatorTitle":[{"kind":"identifier","text":"CVStatusSelected"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/SY":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","title":"Swift.RawRepresentable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/init(rawValue:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/init(rawValue:)","type":"topic","title":"init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/SH":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","title":"Swift.Hashable"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","title":"Swift.Equatable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/highlighted":{"title":"CVStatus.highlighted","role":"symbol","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/highlighted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CVStatusHighlighted"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/highlighted"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/out":{"title":"CVStatus.out","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/out","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/out","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"out"}],"navigatorTitle":[{"text":"CVStatusOut","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/disabled":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/disabled","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/disabled","navigatorTitle":[{"text":"CVStatusDisabled","kind":"identifier"}],"title":"CVStatus.disabled","kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvstatus","type":"topic","title":"CVStatus","navigatorTitle":[{"text":"CVStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVStatus","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVStatus/in":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`in`"}],"title":"CVStatus.in","url":"\/documentation\/gcbuzzkeysdk\/cvstatus\/in","role":"symbol","navigatorTitle":[{"text":"CVStatusIn","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/in"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"CVStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CVStatus","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"CVStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/disabled","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/highlighted","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/in","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/out","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVStatus\/selected"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1selected\/title","op":"replace","value":"CVStatusSelected"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1selected\/fragments","op":"replace","value":[{"text":"CVStatusSelected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1highlighted\/title","op":"replace","value":"CVStatusHighlighted"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1highlighted\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVStatusHighlighted"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1out\/title","op":"replace","value":"CVStatusOut"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1out\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVStatusOut"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1disabled\/title","op":"replace","value":"CVStatusDisabled"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1disabled\/fragments","op":"replace","value":[{"text":"CVStatusDisabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/title","op":"replace","value":"CVStatus"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVStatus"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CVStatus"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1in\/title","op":"replace","value":"CVStatusIn"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVStatus~1in\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVStatusIn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}