{"sections":[],"metadata":{"symbolKind":"enum","role":"symbol","title":"CVWeekdaySymbolType","externalID":"c:@M@GCBuzzKeySDK@E@CVWeekdaySymbolType","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVWeekdaySymbolType"}],"roleHeading":"Enumeration","modules":[{"name":"GCBuzzKeySDK"}]},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/normal","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/short","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/veryShort"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype"]}],"references":{"doc://com.gamechange.GCKeyboard/SY":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","title":"Swift.RawRepresentable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/short":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"short"}],"type":"topic","abstract":[],"title":"CVWeekdaySymbolType.short","navigatorTitle":[{"kind":"identifier","text":"CVWeekdaySymbolTypeShort"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/short","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/short"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/veryShort":{"title":"CVWeekdaySymbolType.veryShort","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"veryShort","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/veryShort","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolTypeVeryShort","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/veryshort"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/init(rawValue:)","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/normal":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/normal","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normal","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/normal","title":"CVWeekdaySymbolType.normal","navigatorTitle":[{"text":"CVWeekdaySymbolTypeNormal","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/equatable-implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/Equatable-Implementations","role":"collectionGroup"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVWeekdaySymbolType"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"kind":"symbol","title":"CVWeekdaySymbolType","type":"topic"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ"},"doc://com.gamechange.GCKeyboard/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CVWeekdaySymbolType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/normal","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/short","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/veryShort"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVWeekdaySymbolType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CVWeekdaySymbolTypeShort","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1short\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CVWeekdaySymbolTypeShort"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1short\/fragments"},{"op":"replace","value":"CVWeekdaySymbolTypeVeryShort","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1veryShort\/title"},{"op":"replace","value":[{"text":"CVWeekdaySymbolTypeVeryShort","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1veryShort\/fragments"},{"op":"replace","value":"CVWeekdaySymbolTypeNormal","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1normal\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CVWeekdaySymbolTypeNormal"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1normal\/fragments"},{"op":"replace","value":"CVWeekdaySymbolType","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title"},{"op":"replace","value":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}