{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/delegate"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/handle(_:open:options:target:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/shared"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"metadata":{"role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardUtils"}],"navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"GCBuzzKeySDK"}],"title":"GCKeyboardUtils","externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils"},"abstract":[{"text":"Access this class in following method of AppDelegate","type":"text"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool","type":"text"},{"text":" ","type":"text"},{"text":"This class will handle deeplink from keyboard to App using URL scheme","type":"text"},{"text":" ","type":"text"},{"text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks","type":"text"}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutils"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtils","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","text":"GCKeyboardUtilsDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/delegate","role":"symbol","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/delegate","kind":"symbol","title":"delegate"},"doc://com.gamechange.GCKeyboard/SH":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","title":"Swift.Hashable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"role":"collection","title":"GCBuzzKeySDK","type":"topic","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","title":"RxSwift.ReactiveCompatible"},"doc://com.gamechange.GCKeyboard/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.gamechange.GCKeyboard/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.gamechange.GCKeyboard/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject","title":"NSObject"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","title":"Swift.Equatable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/handle(_:open:options:target:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey","kind":"typeIdentifier","text":"OpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":")"}],"abstract":[{"text":"Call this class method as shown below in AppDelegate","type":"text"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL,","type":"text"},{"text":" ","type":"text"},{"text":"options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {","type":"text"},{"text":" ","type":"text"},{"text":"GCKeyboardUtils.shared.handle(app, open: url, options: options, target: window.rootViewController!)","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/handle(_:open:options:target:)","navigatorTitle":[{"kind":"identifier","text":"handle:open:options:target:"}],"type":"topic","title":"handle(_:open:options:target:)","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/handle(_:open:options:target:)","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCKeyboard/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils/shared":{"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils\/shared","kind":"symbol","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKeyboardUtils","kind":"typeIdentifier","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCKeyboardUtils"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/shared","role":"symbol"},"doc://com.gamechange.GCKeyboard/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtils":{"abstract":[{"text":"Access this class in following method of AppDelegate","type":"text"},{"text":" ","type":"text"},{"text":"func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool","type":"text"},{"text":" ","type":"text"},{"text":"This class will handle deeplink from keyboard to App using URL scheme","type":"text"},{"text":" ","type":"text"},{"text":"Set the delegate property of GCKeyboardUtils to recieve the callbacks","type":"text"}],"title":"GCKeyboardUtils","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtils","kind":"identifier"}],"navigatorTitle":[{"text":"GCKeyboardUtils","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils","kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutils"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"GCKeyboardUtils","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GCKeyboardUtils"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GCKeyboardUtils","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/delegate"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtils\/handle(_:open:options:target:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardUtils"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1handle(_:open:options:target:)\/title","value":"handle:open:options:target:","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils~1handle(_:open:options:target:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handle:open:options:target:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/title","value":"GCKeyboardUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/fragments","value":[{"text":"GCKeyboardUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtils\/navigatorTitle","value":[{"text":"GCKeyboardUtils","kind":"identifier"}],"op":"replace"}]}]}