{"sections":[],"abstract":[{"text":"GCKeyboardUtilsDelegate returns callback from GCKeyboardUtils for particular action required","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"title":"GCKeyboardUtilsDelegate","externalID":"c:@M@GCBuzzKeySDK@objc(pl)GCKeyboardUtilsDelegate","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}],"role":"symbol","modules":[{"name":"GCBuzzKeySDK"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate\/loginRequiredBySalesKeyboard()"],"anchor":"Instance-Methods","generated":true}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate/loginRequiredBySalesKeyboard()":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate\/loginrequiredbysaleskeyboard()","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginRequiredBySalesKeyboard"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate\/loginRequiredBySalesKeyboard()","title":"loginRequiredBySalesKeyboard()","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginRequiredBySalesKeyboard","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"type":"topic","title":"GCBuzzKeySDK","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","role":"collection","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardUtilsDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gckeyboardutilsdelegate","navigatorTitle":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"role":"symbol","title":"GCKeyboardUtilsDelegate","kind":"symbol","abstract":[{"type":"text","text":"GCKeyboardUtilsDelegate returns callback from GCKeyboardUtils for particular action required"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GCKeyboardUtilsDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardUtilsDelegate\/loginRequiredBySalesKeyboard()"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"loginRequiredBySalesKeyboard","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate~1loginRequiredBySalesKeyboard()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginRequiredBySalesKeyboard"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate~1loginRequiredBySalesKeyboard()\/fragments"},{"value":"GCKeyboardUtilsDelegate","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/title"},{"value":[{"kind":"identifier","text":"GCKeyboardUtilsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/fragments"},{"value":[{"text":"GCKeyboardUtilsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardUtilsDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}