{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(coder:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(nibName:bundle:)"],"anchor":"Initializers"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/pdfViewParentViewController()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewDidLoad()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewWillAppear(_:)"],"anchor":"Instance-Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/PropertyGuruServiceManagerInjected-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentPickerDelegate-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/@M@GCKeyboardKitSDK@objc(cs)GCKeyboardKitViewController"],"kind":"relationships","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController"],"kind":"relationships","title":"Inherited By"},{"type":"conformsTo","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSCoding","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","doc:\/\/com.gamechange.GCKeyboard\/s8CopyableP","doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/s8SendableP","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIAppearanceContainer","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIContentContainer","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentMenuDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentPickerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIFocusEnvironment","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIStateRestoring","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextFieldDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextInputDelegate","doc:\/\/com.gamechange.GCKeyboard\/5UIKit23UITraitChangeObservableP","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITraitEnvironment","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"metadata":{"roleHeading":"Class","externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCSalesKeyBoardViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","modules":[{"name":"GCBuzzKeySDK"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.gamechange.GCKeyboard/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIResponderStandardEditActions"},"doc://com.gamechange.GCKeyboard/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIStateRestoring"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController":{"kind":"symbol","title":"GCKeyboardViewController","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","abstract":[{"text":"Add Custom Keyboard extension to the application.","type":"text"},{"text":" ","type":"text"},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GCKeyboardViewController"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardViewController"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/init(coder:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(coder:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":")"}],"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/init(coder:)","kind":"symbol","title":"init(coder:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},"doc://com.gamechange.GCKeyboard/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/viewWillAppear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewWillAppear(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/init(nibName:bundle:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(nibName:bundle:)","abstract":[],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/init(nibname:bundle:)","kind":"symbol","title":"init(nibName:bundle:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nibName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManagerInjected":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PropertyGuruServiceManagerInjected"}],"title":"PropertyGuruServiceManagerInjected","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/pdfViewParentViewController()":{"kind":"symbol","title":"pdfViewParentViewController()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfViewParentViewController"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/pdfViewParentViewController()","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/pdfviewparentviewcontroller()","role":"symbol"},"doc://com.gamechange.GCKeyboard/objc(pl)UIDocumentPickerDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentPickerDelegate","title":"UIDocumentPickerDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/SQ":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/@M@GCKeyboardKitSDK@objc(cs)GCKeyboardKitViewController":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/@M@GCKeyboardKitSDK@objc(cs)GCKeyboardKitViewController","title":"GCKeyboardKitViewController","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s7CVarArgP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/UIDocumentMenuDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/uidocumentmenudelegate-implementations","kind":"article","title":"UIDocumentMenuDelegate Implementations","role":"collectionGroup","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations"},"doc://com.gamechange.GCKeyboard/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UITextFieldDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextFieldDelegate","title":"UITextFieldDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s8CopyableP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/7RxSwift18ReactiveCompatibleP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/7RxSwift18ReactiveCompatibleP","title":"RxSwift.ReactiveCompatible","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/UIDocumentPickerDelegate-Implementations":{"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/uidocumentpickerdelegate-implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentPickerDelegate-Implementations","title":"UIDocumentPickerDelegate Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.gamechange.GCKeyboard/SH":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIDocumentMenuDelegate":{"title":"UIDocumentMenuDelegate","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentMenuDelegate"},"doc://com.gamechange.GCKeyboard/objc(pl)UITextInputDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextInputDelegate","title":"UIKit.UITextInputDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)NSCoding"},"doc://com.gamechange.GCKeyboard/objc(pl)UINavigationControllerDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UINavigationControllerDelegate","title":"UINavigationControllerDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.gamechange.GCKeyboard/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/5UIKit23UITraitChangeObservableP"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/PropertyGuruServiceManagerInjected-Implementations":{"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanagerinjected-implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/PropertyGuruServiceManagerInjected-Implementations","title":"PropertyGuruServiceManagerInjected Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/viewDidLoad()":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/viewdidload()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","abstract":[]},"doc://com.gamechange.GCKeyboard/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable"},"doc://com.gamechange.GCKeyboard/s8SendableP":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(coder:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(nibName:bundle:)","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewDidLoad()","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/viewWillAppear(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentPickerDelegate-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/@M@GCKeyboardKitSDK@objc(cs)GCKeyboardKitViewController"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController"],"type":"inheritedBy","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentMenuDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UIDocumentPickerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.gamechange.GCKeyboard\/objc(pl)UITextFieldDelegate"],"type":"conformsTo","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"GCKeyboardKitViewController","preciseIdentifier":"c:@M@GCKeyboardKitSDK@objc(cs)GCKeyboardKitViewController","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/title","value":"GCKeyboardViewController"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"GCKeyboardViewController"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GCKeyboardViewController"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(coder:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","op":"replace","value":"GCSalesKeyBoardViewController"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1viewWillAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(nibName:bundle:)\/title","op":"replace","value":"initWithNibName:bundle:"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(nibName:bundle:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]}]}]}