{"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/SQ","doc:\/\/com.gamechange.GCKeyboard\/SH","doc:\/\/com.gamechange.GCKeyboard\/SY"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"HTTPStatusCode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"modules":[{"name":"GCBuzzKeySDK"}],"role":"symbol","symbolKind":"enum","title":"HTTPStatusCode","externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode","roleHeading":"Enumeration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/accepted","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badGateway","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badRequest","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/created","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/forbidden","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/gatewayTimeout","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/httpVersionNotSupported","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/insufficientStorage","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/internalServerError","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/loopDetected","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/networkAuthenticationRequired","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/noContent","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notExtended","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notImplemented","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/okCode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/requestTimeout","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/serviceUnavailable","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unauthorized","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unprocessableEntity","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/variantAlsoNegotiates"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/Equatable-Implementations","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","interfaceLanguage":"swift"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/Equatable-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/Equatable-Implementations","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/equatable-implementations","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/notExtended":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeNotExtended"}],"title":"HTTPStatusCode.notExtended","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notExtended","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notExtended","kind":"identifier"}],"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/notextended"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/networkAuthenticationRequired":{"kind":"symbol","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/networkauthenticationrequired","role":"symbol","navigatorTitle":[{"text":"HTTPStatusCodeNetworkAuthenticationRequired","kind":"identifier"}],"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkAuthenticationRequired","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/networkAuthenticationRequired","title":"HTTPStatusCode.networkAuthenticationRequired"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/internalServerError":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/internalServerError","role":"symbol","abstract":[{"text":"Internal Server Error: 500","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeInternalServerError"}],"title":"HTTPStatusCode.internalServerError","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/internalservererror","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerError"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/noContent":{"title":"HTTPStatusCode.noContent","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noContent","kind":"identifier"}],"abstract":[{"text":"No Content: 204","type":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/noContent","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/nocontent","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeNoContent"}],"kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/badGateway":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badGateway","kind":"symbol","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badGateway","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/badgateway","title":"HTTPStatusCode.badGateway","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeBadGateway"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/SY":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SY","title":"Swift.RawRepresentable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/badRequest":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badRequest","kind":"identifier"}],"title":"HTTPStatusCode.badRequest","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/badrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeBadRequest"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badRequest"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/unauthorized":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unauthorized","abstract":[{"type":"text","text":"Unauthorized: 401"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorized"}],"role":"symbol","navigatorTitle":[{"text":"HTTPStatusCodeUnauthorized","kind":"identifier"}],"title":"HTTPStatusCode.unauthorized","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/unauthorized","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/accepted":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accepted","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/accepted","type":"topic","title":"HTTPStatusCode.accepted","kind":"symbol","role":"symbol","abstract":[{"text":"Accepted: 202","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeAccepted"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/accepted"},"doc://com.gamechange.GCKeyboard/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SQ","title":"Swift.Equatable"},"doc://com.gamechange.GCKeyboard/SH":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCKeyboard\/SH","title":"Swift.Hashable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/okCode":{"navigatorTitle":[{"text":"HTTPStatusCodeOK","kind":"identifier"}],"kind":"symbol","title":"HTTPStatusCode.okCode","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/okcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okCode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"OK: 200","type":"text"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/okCode"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/forbidden":{"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/forbidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"abstract":[{"type":"text","text":"Forbidden: 403"}],"kind":"symbol","title":"HTTPStatusCode.forbidden","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/forbidden","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}],"type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/unprocessableEntity":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unprocessableEntity"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/unprocessableentity","abstract":[{"text":"Unprocessable Entity: 422","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"HTTPStatusCodeUnprocessableEntity","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unprocessableEntity","title":"HTTPStatusCode.unprocessableEntity","type":"topic"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/created":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeCreated"}],"title":"HTTPStatusCode.created","abstract":[{"type":"text","text":"Created: 201"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/created","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/created","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/init(rawvalue:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/requestTimeout":{"role":"symbol","kind":"symbol","title":"HTTPStatusCode.requestTimeout","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeRequestTimeout"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimeout"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/requesttimeout","abstract":[{"text":"Request Timeout: 408","type":"text"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/requestTimeout"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/serviceUnavailable":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/serviceUnavailable","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/serviceunavailable","navigatorTitle":[{"text":"HTTPStatusCodeServiceUnavailable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceUnavailable","kind":"identifier"}],"title":"HTTPStatusCode.serviceUnavailable"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/httpVersionNotSupported":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/httpVersionNotSupported","type":"topic","title":"HTTPStatusCode.httpVersionNotSupported","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/httpversionnotsupported","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpVersionNotSupported","kind":"identifier"}],"navigatorTitle":[{"text":"HTTPStatusCodeHttpVersionNotSupported","kind":"identifier"}],"abstract":[{"type":"text","text":"Internal Server Error: 500"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/rawrepresentable-implementations"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/loopDetected":{"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/loopdetected","title":"HTTPStatusCode.loopDetected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopDetected","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/loopDetected","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeLoopDetected"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/gatewayTimeout":{"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/gatewaytimeout","title":"HTTPStatusCode.gatewayTimeout","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayTimeout"}],"type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/gatewayTimeout","navigatorTitle":[{"text":"HTTPStatusCodeGatewayTimeout","kind":"identifier"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/variantAlsoNegotiates":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/variantalsonegotiates","role":"symbol","navigatorTitle":[{"text":"HTTPStatusCodeVariantAlsoNegotiates","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/variantAlsoNegotiates","title":"HTTPStatusCode.variantAlsoNegotiates","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"variantAlsoNegotiates"}],"kind":"symbol","abstract":[{"type":"text","text":"Internal Server Error: 500"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/notImplemented":{"role":"symbol","abstract":[{"type":"text","text":"Internal Server Error: 500"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeNotImplemented"}],"title":"HTTPStatusCode.notImplemented","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notImplemented","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/notimplemented","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notImplemented"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/insufficientStorage":{"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/insufficientstorage","title":"HTTPStatusCode.insufficientStorage","type":"topic","navigatorTitle":[{"text":"HTTPStatusCodeInsufficientStorage","kind":"identifier"}],"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/insufficientStorage","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insufficientStorage","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"HTTPStatusCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"HTTPStatusCode","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"HTTPStatusCode","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/accepted","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badGateway","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/badRequest","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/created","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/forbidden","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/gatewayTimeout","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/httpVersionNotSupported","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/insufficientStorage","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/internalServerError","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/loopDetected","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/networkAuthenticationRequired","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/noContent","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notExtended","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/notImplemented","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/okCode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/requestTimeout","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/serviceUnavailable","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unauthorized","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unprocessableEntity","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/variantAlsoNegotiates"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPStatusCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1notExtended\/title","op":"replace","value":"HTTPStatusCodeNotExtended"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1notExtended\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeNotExtended"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1networkAuthenticationRequired\/title","op":"replace","value":"HTTPStatusCodeNetworkAuthenticationRequired"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1networkAuthenticationRequired\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeNetworkAuthenticationRequired","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1internalServerError\/title","op":"replace","value":"HTTPStatusCodeInternalServerError"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1internalServerError\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeInternalServerError"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1noContent\/title","op":"replace","value":"HTTPStatusCodeNoContent"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1noContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeNoContent"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badGateway\/title","op":"replace","value":"HTTPStatusCodeBadGateway"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badGateway\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeBadGateway"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","op":"replace","value":"HTTPStatusCode"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","op":"replace","value":[{"text":"HTTPStatusCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","op":"replace","value":[{"text":"HTTPStatusCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badRequest\/title","op":"replace","value":"HTTPStatusCodeBadRequest"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1badRequest\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeBadRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unauthorized\/title","op":"replace","value":"HTTPStatusCodeUnauthorized"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unauthorized\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeUnauthorized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1accepted\/title","op":"replace","value":"HTTPStatusCodeAccepted"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1accepted\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeAccepted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1okCode\/title","op":"replace","value":"HTTPStatusCodeOK"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1okCode\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeOK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1forbidden\/title","op":"replace","value":"HTTPStatusCodeForbidden"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1forbidden\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeForbidden","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unprocessableEntity\/title","op":"replace","value":"HTTPStatusCodeUnprocessableEntity"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unprocessableEntity\/fragments","op":"replace","value":[{"text":"HTTPStatusCodeUnprocessableEntity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1created\/title","op":"replace","value":"HTTPStatusCodeCreated"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1created\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeCreated"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1requestTimeout\/title","op":"replace","value":"HTTPStatusCodeRequestTimeout"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1requestTimeout\/fragments","op":"replace","value":[{"kind":"identifier","text":"HTTPStatusCodeRequestTimeout"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1serviceUnavailable\/title","value":"HTTPStatusCodeServiceUnavailable","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1serviceUnavailable\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeServiceUnavailable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1httpVersionNotSupported\/title","value":"HTTPStatusCodeHttpVersionNotSupported","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1httpVersionNotSupported\/fragments","value":[{"text":"HTTPStatusCodeHttpVersionNotSupported","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1loopDetected\/title","value":"HTTPStatusCodeLoopDetected","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1loopDetected\/fragments","value":[{"text":"HTTPStatusCodeLoopDetected","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1gatewayTimeout\/title","value":"HTTPStatusCodeGatewayTimeout","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1gatewayTimeout\/fragments","value":[{"text":"HTTPStatusCodeGatewayTimeout","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1variantAlsoNegotiates\/title","value":"HTTPStatusCodeVariantAlsoNegotiates","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1variantAlsoNegotiates\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeVariantAlsoNegotiates"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1notImplemented\/title","value":"HTTPStatusCodeNotImplemented","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1notImplemented\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeNotImplemented"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1insufficientStorage\/title","value":"HTTPStatusCodeInsufficientStorage","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1insufficientStorage\/fragments","value":[{"text":"HTTPStatusCodeInsufficientStorage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}