{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected"]}],"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"]}],"metadata":{"title":"PropertyGuruServiceManagerInjected","role":"symbol","externalID":"s:12GCBuzzKeySDK34PropertyGuruServiceManagerInjectedP","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PropertyGuruServiceManagerInjected"}],"navigatorTitle":[{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"modules":[{"name":"GCBuzzKeySDK"}]},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected\/propertyGuruServiceManager"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManagerInjected":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PropertyGuruServiceManagerInjected","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PropertyGuruServiceManagerInjected"}],"title":"PropertyGuruServiceManagerInjected","abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"title":"GCSalesKeyBoardViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCKeyboardViewController":{"kind":"symbol","title":"GCKeyboardViewController","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCKeyboardViewController","abstract":[{"text":"Add Custom Keyboard extension to the application.","type":"text"},{"text":" ","type":"text"},{"text":"File > New > Target > Custom Keyboard extension.","type":"text"},{"text":" ","type":"text"},{"text":"Inherit  KeyboardViewController class with GCKeyboardViewController","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GCKeyboardViewController"}],"url":"\/documentation\/gcbuzzkeysdk\/gckeyboardviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCKeyboardViewController"}],"role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/PropertyGuruServiceManagerInjected/propertyGuruServiceManager":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyGuruServiceManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PropertyGuruServiceManager","preciseIdentifier":"s:12GCBuzzKeySDK26PropertyGuruServiceManagerC"}],"title":"propertyGuruServiceManager","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/PropertyGuruServiceManagerInjected\/propertyGuruServiceManager","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/propertyguruservicemanagerinjected\/propertyguruservicemanager","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"GCSalesKeyBoardViewController","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title"},{"op":"replace","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle"},{"op":"replace","value":"GCKeyboardViewController","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/title"},{"op":"replace","value":[{"text":"GCKeyboardViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GCKeyboardViewController"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCKeyboardViewController\/navigatorTitle"}]}]}