{"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/documentMenu(_:didPickDocumentPicker:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIDocumentMenuDelegate.documentMenu(_:didPickDocumentPicker:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"documentMenu","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentMenuViewController","preciseIdentifier":"c:objc(cs)UIDocumentMenuViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didPickDocumentPicker","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/documentmenu(_:didpickdocumentpicker:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/documentmenu(_:didpickdocumentpicker:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@CM@GCBuzzKeySDK@objc(cs)GCSalesKeyBoardViewController(im)documentMenu:didPickDocumentPicker:","role":"symbol","navigatorTitle":[{"text":"documentMenu:didPickDocumentPicker:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GCBuzzKeySDK"}],"extendedModule":"GCBuzzKeySDK","title":"documentMenu(_:didPickDocumentPicker:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentMenuViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentMenuViewController"},{"text":", ","kind":"text"},{"text":"didPickDocumentPicker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"kind":"symbol","title":"GCSalesKeyBoardViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/documentMenu(_:didPickDocumentPicker:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/documentMenu(_:didPickDocumentPicker:)","navigatorTitle":[{"text":"documentMenu:didPickDocumentPicker:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/documentmenu(_:didpickdocumentpicker:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentMenuViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentMenuViewController"},{"text":", ","kind":"text"},{"text":"didPickDocumentPicker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":")","kind":"text"}],"title":"documentMenu(_:didPickDocumentPicker:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"type":"topic","title":"GCBuzzKeySDK","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","role":"collection","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/UIDocumentMenuDelegate-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/uidocumentmenudelegate-implementations","title":"UIDocumentMenuDelegate Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"documentMenu:didPickDocumentPicker:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentMenu:didPickDocumentPicker:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentMenu:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentMenuViewController","text":"UIDocumentMenuViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentMenu","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didPickDocumentPicker:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentPicker","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1documentMenu(_:didPickDocumentPicker:)\/title","value":"documentMenu:didPickDocumentPicker:"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1documentMenu(_:didPickDocumentPicker:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentMenu:didPickDocumentPicker:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}