{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"]]},"kind":"symbol","metadata":{"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCSalesKeyBoardViewController(im)initWithNibName:bundle:","modules":[{"name":"GCBuzzKeySDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?)"}],"title":"init(nibName:bundle:)","roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(nibName:bundle:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"type":"topic","title":"GCBuzzKeySDK","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","role":"collection","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/init(nibName:bundle:)":{"title":"init(nibName:bundle:)","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/init(nibName:bundle:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nibName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/init(nibname:bundle:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"kind":"symbol","title":"GCSalesKeyBoardViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithNibName:bundle:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(nibName:bundle:)\/title","value":"initWithNibName:bundle:","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1init(nibName:bundle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}