{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/propertyGuruServiceManager"],"title":"Instance Properties"}],"kind":"article","variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanagerinjected-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/PropertyGuruServiceManagerInjected-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"]]},"sections":[],"metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"role":"collectionGroup","roleHeading":"API Collection","title":"PropertyGuruServiceManagerInjected Implementations"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/propertyGuruServiceManager":{"title":"propertyGuruServiceManager","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/propertyGuruServiceManager","kind":"symbol","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/propertyguruservicemanager","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyGuruServiceManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12GCBuzzKeySDK26PropertyGuruServiceManagerC","text":"PropertyGuruServiceManager","kind":"typeIdentifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"abstract":[],"title":"GCSalesKeyBoardViewController","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller","navigatorTitle":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}