{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController"]]},"metadata":{"role":"collectionGroup","title":"UIDocumentMenuDelegate Implementations","modules":[{"name":"GCBuzzKeySDK"}],"roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/UIDocumentMenuDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/documentMenu(_:didPickDocumentPicker:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/uidocumentmenudelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/uidocumentmenudelegate-implementations"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController/documentMenu(_:didPickDocumentPicker:)":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/documentMenu(_:didPickDocumentPicker:)","navigatorTitle":[{"text":"documentMenu:didPickDocumentPicker:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller\/documentmenu(_:didpickdocumentpicker:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentMenuViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentMenuViewController"},{"text":", ","kind":"text"},{"text":"didPickDocumentPicker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":")","kind":"text"}],"title":"documentMenu(_:didPickDocumentPicker:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}],"type":"topic","title":"GCBuzzKeySDK","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","role":"collection","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCSalesKeyBoardViewController":{"kind":"symbol","title":"GCSalesKeyBoardViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController","url":"\/documentation\/gcbuzzkeysdk\/gcsaleskeyboardviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCSalesKeyBoardViewController\/documentMenu(_:didPickDocumentPicker:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1documentMenu(_:didPickDocumentPicker:)\/title","value":"documentMenu:didPickDocumentPicker:"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController~1documentMenu(_:didPickDocumentPicker:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentMenu:didPickDocumentPicker:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/title","value":"GCSalesKeyBoardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/fragments","value":[{"text":"GCSalesKeyBoardViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCSalesKeyBoardViewController\/navigatorTitle","value":[{"kind":"identifier","text":"GCSalesKeyBoardViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}