{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"]]},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/clear()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"This method clear all userDefaults"}],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"clear()","modules":[{"name":"GCBuzzKeySDK"}],"externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults(im)clear","navigatorTitle":[{"text":"clear","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"()"}]},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/clear()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/clear()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"role":"collection","title":"GCBuzzKeySDK","type":"topic","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/clear()":{"role":"symbol","abstract":[{"type":"text","text":"This method clear all userDefaults"}],"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/clear()","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/clear()","title":"clear()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"clear","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"clear"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clear","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title","op":"replace","value":"GCUserDefaults"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments","op":"replace","value":[{"kind":"identifier","text":"GCUserDefaults"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle","op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1clear()\/title","op":"replace","value":"clear"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1clear()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clear"}]}]}]}