{"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setLoginToken(token:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults(im)setLoginTokenWithToken:","role":"symbol","symbolKind":"method","title":"setLoginToken(token:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLoginToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"GCBuzzKeySDK"}],"navigatorTitle":[{"kind":"identifier","text":"setLoginTokenWithToken:"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLoginToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setlogintoken(token:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setlogintoken(token:)"]}],"abstract":[{"type":"text","text":"Set Login Access token using this method"}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"kind":"symbol","url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/setLoginToken(token:)":{"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/setlogintoken(token:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"setLoginTokenWithToken:","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/setLoginToken(token:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoginToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Set Login Access token using this method"}],"title":"setLoginToken(token:)","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"role":"collection","title":"GCBuzzKeySDK","type":"topic","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setLoginTokenWithToken:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setLoginTokenWithToken:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLoginTokenWithToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"GCUserDefaults","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title"},{"op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments"},{"op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle"},{"op":"replace","value":"setLoginTokenWithToken:","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setLoginToken(token:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLoginTokenWithToken:"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults~1setLoginToken(token:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}