{"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"]]},"metadata":{"symbolKind":"property","externalID":"s:12GCBuzzKeySDK14GCUserDefaultsC6sharedACvpZ","modules":[{"name":"GCBuzzKeySDK"}],"title":"shared","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults","text":"GCUserDefaults","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/shared"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCUserDefaults","kind":"typeIdentifier","preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/shared"},"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults":{"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GCUserDefaults"}],"title":"GCUserDefaults","navigatorTitle":[{"kind":"identifier","text":"GCUserDefaults"}],"abstract":[{"type":"text","text":"Use GCUserDefaults class to pass data from app to SDK using Singletion shared object"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/GCUserDefaults/shared":{"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/GCUserDefaults\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GCBuzzKeySDK@objc(cs)GCUserDefaults","text":"GCUserDefaults","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/gcuserdefaults\/shared","title":"shared","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"GCUserDefaults","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/title"},{"op":"replace","value":[{"text":"GCUserDefaults","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GCUserDefaults"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1GCUserDefaults\/navigatorTitle"}]}]}