{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"friday"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday"]]},"kind":"symbol","metadata":{"externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarWeekday@CVCalendarWeekdayFriday","modules":[{"name":"GCBuzzKeySDK"}],"symbolKind":"case","title":"CVCalendarWeekday.friday","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friday","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"CVCalendarWeekdayFriday","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/friday","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/friday"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/friday"]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday":{"kind":"symbol","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday","type":"topic","abstract":[],"title":"CVCalendarWeekday","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/friday":{"kind":"symbol","role":"symbol","title":"CVCalendarWeekday.friday","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/friday","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/friday","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friday","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CVCalendarWeekdayFriday"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"CVCalendarWeekdayFriday","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CVCalendarWeekdayFriday","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CVCalendarWeekdayFriday"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/title","value":"CVCalendarWeekday","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekday"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/navigatorTitle","value":[{"text":"CVCalendarWeekday","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1friday\/title","value":"CVCalendarWeekdayFriday","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1friday\/fragments","value":[{"text":"CVCalendarWeekdayFriday","kind":"identifier"}],"op":"replace"}]}]}