{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/sunday"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/sunday"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/sunday"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sunday","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"metadata":{"modules":[{"name":"GCBuzzKeySDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sunday"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"CVCalendarWeekday.sunday","navigatorTitle":[{"kind":"identifier","text":"CVCalendarWeekdaySunday"}],"externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarWeekday@CVCalendarWeekdaySunday"},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday","title":"CVCalendarWeekday","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/sunday":{"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/sunday","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sunday","kind":"identifier"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/sunday","navigatorTitle":[{"text":"CVCalendarWeekdaySunday","kind":"identifier"}],"abstract":[],"type":"topic","title":"CVCalendarWeekday.sunday","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"CVCalendarWeekdaySunday"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CVCalendarWeekdaySunday","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"CVCalendarWeekdaySunday","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/title","op":"replace","value":"CVCalendarWeekday"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/fragments","op":"replace","value":[{"text":"CVCalendarWeekday","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CVCalendarWeekday"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1sunday\/title","op":"replace","value":"CVCalendarWeekdaySunday"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1sunday\/fragments","op":"replace","value":[{"kind":"identifier","text":"CVCalendarWeekdaySunday"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}