{"metadata":{"title":"CVCalendarWeekday.tuesday","navigatorTitle":[{"text":"CVCalendarWeekdayTuesday","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"GCBuzzKeySDK"}],"role":"symbol","externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarWeekday@CVCalendarWeekdayTuesday","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tuesday","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/tuesday"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tuesday"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/tuesday"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/tuesday"]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday":{"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday","title":"CVCalendarWeekday","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday","navigatorTitle":[{"text":"CVCalendarWeekday","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarWeekday","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarWeekday/tuesday":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tuesday","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarWeekday\/tuesday","title":"CVCalendarWeekday.tuesday","navigatorTitle":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarweekday\/tuesday"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CVCalendarWeekdayTuesday","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CVCalendarWeekday","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CVCalendarWeekday"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CVCalendarWeekday"}],"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1tuesday\/title","op":"replace","value":"CVCalendarWeekdayTuesday"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarWeekday~1tuesday\/fragments","value":[{"kind":"identifier","text":"CVCalendarWeekdayTuesday"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}