{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/monthview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/monthview"]}],"sections":[],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/monthView","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"monthView","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"CVCalendarViewPresentationModeMonthView","kind":"identifier"}],"role":"symbol","externalID":"c:@M@GCBuzzKeySDK@E@CVCalendarViewPresentationMode@CVCalendarViewPresentationModeMonthView","title":"CVCalendarViewPresentationMode.monthView","modules":[{"name":"GCBuzzKeySDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"monthView"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode/monthView":{"role":"symbol","kind":"symbol","title":"CVCalendarViewPresentationMode.monthView","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode\/monthView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVCalendarViewPresentationModeMonthView"}],"url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode\/monthview","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"monthView"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVCalendarViewPresentationMode":{"type":"topic","title":"CVCalendarViewPresentationMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVCalendarViewPresentationMode","url":"\/documentation\/gcbuzzkeysdk\/cvcalendarviewpresentationmode","kind":"symbol","navigatorTitle":[{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","type":"topic","role":"collection","url":"\/documentation\/gcbuzzkeysdk","title":"GCBuzzKeySDK","abstract":[{"text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"CVCalendarViewPresentationModeMonthView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CVCalendarViewPresentationModeMonthView","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"CVCalendarViewPresentationModeMonthView"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1monthView\/title","value":"CVCalendarViewPresentationModeMonthView","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode~1monthView\/fragments","value":[{"kind":"identifier","text":"CVCalendarViewPresentationModeMonthView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/title","value":"CVCalendarViewPresentationMode","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/fragments","value":[{"text":"CVCalendarViewPresentationMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVCalendarViewPresentationMode\/navigatorTitle","value":[{"kind":"identifier","text":"CVCalendarViewPresentationMode"}],"op":"replace"}]}]}