{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]}],"metadata":{"title":"!=(_:_:)","modules":[{"name":"GCBuzzKeySDK","relatedModules":["Swift"]}],"roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@GCBuzzKeySDK@E@CVWeekdaySymbolType","extendedModule":"Swift"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/!=(_:_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/Equatable-Implementations"]]},"kind":"symbol","references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/Equatable-Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/equatable-implementations"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"title":"CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","kind":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/!=(_:_:)":{"kind":"symbol","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/!=(_:_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title","value":"CVWeekdaySymbolType"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments","value":[{"text":"CVWeekdaySymbolType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}]}]}]}