{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:12GCBuzzKeySDK19CVWeekdaySymbolTypeO8rawValueACSgSi_tcfc","symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"GCBuzzKeySDK"}],"title":"init(rawValue:)"},"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/init(rawValue:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType"]]},"sections":[],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"title":"CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","kind":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/init(rawValue:)":{"type":"topic","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title","value":"CVWeekdaySymbolType","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}