{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/short"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/short"]}],"metadata":{"externalID":"c:@M@GCBuzzKeySDK@E@CVWeekdaySymbolType@CVWeekdaySymbolTypeShort","roleHeading":"Case","modules":[{"name":"GCBuzzKeySDK"}],"navigatorTitle":[{"kind":"identifier","text":"CVWeekdaySymbolTypeShort"}],"role":"symbol","title":"CVWeekdaySymbolType.short","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"short","kind":"identifier"}],"symbolKind":"case"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/short"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"short"}],"platforms":["iOS"]}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType/short":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"short"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType\/short","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype\/short","title":"CVWeekdaySymbolType.short","type":"topic","abstract":[],"navigatorTitle":[{"text":"CVWeekdaySymbolTypeShort","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/CVWeekdaySymbolType":{"title":"CVWeekdaySymbolType","url":"\/documentation\/gcbuzzkeysdk\/cvweekdaysymboltype","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVWeekdaySymbolType","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/CVWeekdaySymbolType","kind":"symbol","navigatorTitle":[{"text":"CVWeekdaySymbolType","kind":"identifier"}],"abstract":[]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"CVWeekdaySymbolTypeShort","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CVWeekdaySymbolTypeShort","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"CVWeekdaySymbolTypeShort","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1short\/title","value":"CVWeekdaySymbolTypeShort","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType~1short\/fragments","value":[{"kind":"identifier","text":"CVWeekdaySymbolTypeShort"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/title","value":"CVWeekdaySymbolType","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/fragments","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1CVWeekdaySymbolType\/navigatorTitle","value":[{"kind":"identifier","text":"CVWeekdaySymbolType"}],"op":"replace"}]}]}