{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gatewayTimeout","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeGatewayTimeout","navigatorTitle":[{"text":"HTTPStatusCodeGatewayTimeout","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gatewayTimeout","kind":"identifier"}],"title":"HTTPStatusCode.gatewayTimeout","symbolKind":"case","modules":[{"name":"GCBuzzKeySDK"}]},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"sections":[],"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"identifier":{"url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/gatewayTimeout","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/gatewaytimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/gatewaytimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/gatewayTimeout":{"abstract":[{"text":"Internal Server Error: 500","type":"text"}],"title":"HTTPStatusCode.gatewayTimeout","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/gatewaytimeout","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/gatewayTimeout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeGatewayTimeout"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayTimeout"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[],"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HTTPStatusCodeGatewayTimeout","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HTTPStatusCodeGatewayTimeout"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"HTTPStatusCodeGatewayTimeout"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HTTPStatusCodeGatewayTimeout","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1gatewayTimeout\/title"},{"value":[{"kind":"identifier","text":"HTTPStatusCodeGatewayTimeout"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1gatewayTimeout\/fragments"},{"value":"HTTPStatusCode","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title"},{"value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments"},{"value":[{"kind":"identifier","text":"HTTPStatusCode"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}