{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/hash(into:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"GCBuzzKeySDK","relatedModules":["Swift"]}],"title":"hash(into:)","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@GCBuzzKeySDK@E@HTTPStatusCode","symbolKind":"method","extendedModule":"Swift","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/RawRepresentable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[],"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","type":"topic","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/hash(into:)":{"type":"topic","title":"hash(into:)","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/hash(into:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/hash(into:)"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/RawRepresentable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/RawRepresentable-Implementations","kind":"article"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments","value":[{"text":"HTTPStatusCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle","value":[{"text":"HTTPStatusCode","kind":"identifier"}]}]}]}