{"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"HTTPStatusCodeUnprocessableEntity","kind":"identifier"}],"title":"HTTPStatusCode.unprocessableEntity","roleHeading":"Case","symbolKind":"case","modules":[{"name":"GCBuzzKeySDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unprocessableEntity","kind":"identifier"}],"externalID":"c:@M@GCBuzzKeySDK@E@HTTPStatusCode@HTTPStatusCodeUnprocessableEntity"},"abstract":[{"type":"text","text":"Unprocessable Entity: 422"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unprocessableEntity"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unprocessableEntity","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/unprocessableentity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gcbuzzkeysdk\/httpstatuscode\/unprocessableentity"]}],"references":{"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode":{"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[],"title":"HTTPStatusCode","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"role":"symbol","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode","type":"topic","kind":"symbol"},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK/HTTPStatusCode/unprocessableEntity":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK\/HTTPStatusCode\/unprocessableEntity","type":"topic","url":"\/documentation\/gcbuzzkeysdk\/httpstatuscode\/unprocessableentity","title":"HTTPStatusCode.unprocessableEntity","navigatorTitle":[{"text":"HTTPStatusCodeUnprocessableEntity","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Unprocessable Entity: 422"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unprocessableEntity","kind":"identifier"}]},"doc://com.gamechange.GCKeyboard/documentation/GCBuzzKeySDK":{"kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"GCBuzzKeySDK is a framework that provides functionalities for custom keyboard integration in iOS applications with dynamic hotkeys powered by your backend APIs. The SDK handles:"}],"identifier":"doc:\/\/com.gamechange.GCKeyboard\/documentation\/GCBuzzKeySDK","title":"GCBuzzKeySDK","url":"\/documentation\/gcbuzzkeysdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HTTPStatusCodeUnprocessableEntity","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"HTTPStatusCodeUnprocessableEntity","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HTTPStatusCodeUnprocessableEntity"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HTTPStatusCode","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/title"},{"value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/fragments"},{"value":[{"text":"HTTPStatusCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode\/navigatorTitle"},{"value":"HTTPStatusCodeUnprocessableEntity","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unprocessableEntity\/title"},{"value":[{"kind":"identifier","text":"HTTPStatusCodeUnprocessableEntity"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCKeyboard~1documentation~1GCBuzzKeySDK~1HTTPStatusCode~1unprocessableEntity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}